name: Build and deploy
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install deps
              run: npm ci
            - name: Build projects
              run: npm run build
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                path: build
                name: build-files
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get build project
              uses: actions/download-artifact@v4
              with:
                name: build-files
